
package cz.cuni.mff.ms.brodecva.ws.adverts.published.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Tue May 24 10:52:23 CEST 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getAdvert", namespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAdvert", namespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/")

public class GetAdvert {

    @XmlElement(name = "arg0")
    private long arg0;

    public long getArg0() {
        return this.arg0;
    }

    public void setArg0(long newArg0)  {
        this.arg0 = newArg0;
    }

}

