
package cz.cuni.mff.ms.brodecva.ws.adverts.published.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Tue May 24 10:52:23 CEST 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "searchPhoneResponse", namespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchPhoneResponse", namespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/")

public class SearchPhoneResponse {

    @XmlElement(name = "return")
    private cz.cuni.mff.ms.brodecva.ws.adverts.model.Advert[] _return;

    public cz.cuni.mff.ms.brodecva.ws.adverts.model.Advert[] getReturn() {
        return this._return;
    }

    public void setReturn(cz.cuni.mff.ms.brodecva.ws.adverts.model.Advert[] new_return)  {
        this._return = new_return;
    }

}

