
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cz.cuni.mff.ms.brodecva.ws.adverts.published;
import java.util.Arrays;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

import cz.cuni.mff.ms.brodecva.ws.adverts.model.Advert;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-24T10:53:09.495+02:00
 * Generated source version: 2.7.18
 * 
 */
public class AdvertServiceClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", "AdvertService");
        QName portName = new QName("http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", "AdvertServicePort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        //"http://localhost:8080/Adverts/services/AdvertServicePort"); 
        				"http://api.abor.cz/Adverts/services/AdvertServicePort");
        cz.cuni.mff.ms.brodecva.ws.adverts.published.AdvertService client = service.getPort(portName,  cz.cuni.mff.ms.brodecva.ws.adverts.published.AdvertService.class);
        
        System.out.println("id = 115441341:");
        Advert a = client.getAdvert(115441341);
        System.out.println(a);
        System.out.println();
        
        System.out.println("phone = 734200891:");
        Advert[] b = client.searchPhone("734200891");
        System.out.println(Arrays.toString(b));
        System.out.println();
        
        System.out.println("email = tomas.lexa@kontaktservis.cz:");
        Advert[] c = client.searchEmail("tomas.lexa@kontaktservis.cz");
        System.out.println(Arrays.toString(c));
        System.out.println();
        
        System.out.println("published between 2015-03-02 17:59 and 2015-03-02 18:30:");
        Advert[] d = client.listPublished("2015-03-02 17:59", "2015-03-02 18:30");
        System.out.println(Arrays.toString(d));
        System.out.println();
        
        System.out.println("include pronajem, byty and exclude jihocesky, domy:");
        Advert[] e = client.searchTags(new String[] { "pronajem", "praha" }, new String[] { "jihocesky", "domy" });
        System.out.println(Arrays.toString(e));
        System.out.println();
    }

}