
package cz.cuni.mff.ms.brodecva.ws.adverts.published;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-24T10:53:09.444+02:00
 * Generated source version: 2.7.18
 * 
 */
 
public class AdvertServiceServer{

    protected AdvertServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new cz.cuni.mff.ms.brodecva.ws.adverts.published.AdvertServiceImpl();
        String address = "http://localhost:8080/Adverts/services/AdvertServicePort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new AdvertServiceServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 