package cz.cuni.mff.ms.brodecva.ws.adverts.published;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-25T21:52:49.132+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "AdvertService", 
                  wsdlLocation = "file:/C:/Users/user/Documents/Vysoká škola/Cvičení/Webové služby/workspace2/Adverts/WebContent/wsdl/advertserviceimpl.wsdl",
                  targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/") 
public class AdvertService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", "AdvertService");
    public final static QName AdvertServicePort = new QName("http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", "AdvertServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/user/Documents/Vysoká škola/Cvičení/Webové služby/workspace2/Adverts/WebContent/wsdl/advertserviceimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdvertService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/user/Documents/Vysoká škola/Cvičení/Webové služby/workspace2/Adverts/WebContent/wsdl/advertserviceimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AdvertService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdvertService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdvertService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdvertService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdvertService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdvertService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AdvertService
     */
    @WebEndpoint(name = "AdvertServicePort")
    public AdvertService getAdvertServicePort() {
        return super.getPort(AdvertServicePort, AdvertService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdvertService
     */
    @WebEndpoint(name = "AdvertServicePort")
    public AdvertService getAdvertServicePort(WebServiceFeature... features) {
        return super.getPort(AdvertServicePort, AdvertService.class, features);
    }

}
