package cz.cuni.mff.ms.brodecva.ws.adverts.published;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-25T21:52:49.120+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", name = "AdvertService")
@XmlSeeAlso({ObjectFactory.class})
public interface AdvertService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAdvert", targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", className = "cz.cuni.mff.ms.brodecva.ws.adverts.published.GetAdvert")
    @WebMethod
    @ResponseWrapper(localName = "getAdvertResponse", targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", className = "cz.cuni.mff.ms.brodecva.ws.adverts.published.GetAdvertResponse")
    public cz.cuni.mff.ms.brodecva.ws.adverts.published.Advert getAdvert(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listPublished", targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", className = "cz.cuni.mff.ms.brodecva.ws.adverts.published.ListPublished")
    @WebMethod
    @ResponseWrapper(localName = "listPublishedResponse", targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", className = "cz.cuni.mff.ms.brodecva.ws.adverts.published.ListPublishedResponse")
    public java.util.List<cz.cuni.mff.ms.brodecva.ws.adverts.published.Advert> listPublished(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchPhone", targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", className = "cz.cuni.mff.ms.brodecva.ws.adverts.published.SearchPhone")
    @WebMethod
    @ResponseWrapper(localName = "searchPhoneResponse", targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", className = "cz.cuni.mff.ms.brodecva.ws.adverts.published.SearchPhoneResponse")
    public java.util.List<cz.cuni.mff.ms.brodecva.ws.adverts.published.Advert> searchPhone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchTags", targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", className = "cz.cuni.mff.ms.brodecva.ws.adverts.published.SearchTags")
    @WebMethod
    @ResponseWrapper(localName = "searchTagsResponse", targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", className = "cz.cuni.mff.ms.brodecva.ws.adverts.published.SearchTagsResponse")
    public java.util.List<cz.cuni.mff.ms.brodecva.ws.adverts.published.Advert> searchTags(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "searchEmail", targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", className = "cz.cuni.mff.ms.brodecva.ws.adverts.published.SearchEmail")
    @WebMethod
    @ResponseWrapper(localName = "searchEmailResponse", targetNamespace = "http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", className = "cz.cuni.mff.ms.brodecva.ws.adverts.published.SearchEmailResponse")
    public java.util.List<cz.cuni.mff.ms.brodecva.ws.adverts.published.Advert> searchEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
