
package cz.cuni.mff.ms.brodecva.ws.adverts.published;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-25T21:52:48.966+02:00
 * Generated source version: 2.7.18
 * 
 */
public final class AdvertService_AdvertServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://published.adverts.ws.brodecva.ms.mff.cuni.cz/", "AdvertService");

    private AdvertService_AdvertServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AdvertService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AdvertService_Service ss = new AdvertService_Service(wsdlURL, SERVICE_NAME);
        AdvertService port = ss.getAdvertServicePort();  
        
        {
        System.out.println("Invoking getAdvert...");
        long _getAdvert_arg0 = 0;
        cz.cuni.mff.ms.brodecva.ws.adverts.published.Advert _getAdvert__return = port.getAdvert(_getAdvert_arg0);
        System.out.println("getAdvert.result=" + _getAdvert__return);


        }
        {
        System.out.println("Invoking listPublished...");
        java.lang.String _listPublished_arg0 = "";
        java.lang.String _listPublished_arg1 = "";
        java.util.List<cz.cuni.mff.ms.brodecva.ws.adverts.published.Advert> _listPublished__return = port.listPublished(_listPublished_arg0, _listPublished_arg1);
        System.out.println("listPublished.result=" + _listPublished__return);


        }
        {
        System.out.println("Invoking searchPhone...");
        java.lang.String _searchPhone_arg0 = "";
        java.util.List<cz.cuni.mff.ms.brodecva.ws.adverts.published.Advert> _searchPhone__return = port.searchPhone(_searchPhone_arg0);
        System.out.println("searchPhone.result=" + _searchPhone__return);


        }
        {
        System.out.println("Invoking searchTags...");
        java.util.List<java.lang.String> _searchTags_arg0 = null;
        java.util.List<java.lang.String> _searchTags_arg1 = null;
        java.util.List<cz.cuni.mff.ms.brodecva.ws.adverts.published.Advert> _searchTags__return = port.searchTags(_searchTags_arg0, _searchTags_arg1);
        System.out.println("searchTags.result=" + _searchTags__return);


        }
        {
        System.out.println("Invoking searchEmail...");
        java.lang.String _searchEmail_arg0 = "";
        java.util.List<cz.cuni.mff.ms.brodecva.ws.adverts.published.Advert> _searchEmail__return = port.searchEmail(_searchEmail_arg0);
        System.out.println("searchEmail.result=" + _searchEmail__return);


        }

        System.exit(0);
    }

}
